service: perp-arbitrageur

plugins:
    - serverless-offline
    - serverless-dotenv-plugin
    - serverless-webpack

provider:
    name: aws
    runtime: nodejs12.x
    memorySize: 256
    timeout: 60
    versionFunctions: false
    apiGateway:
        minimumCompressionSize: 1024
    stage: production
    region: ap-northeast-1
    environment:
    iamRoleStatements:
        - Effect: Allow
          Action:
              - dynamodb:Query
              - dynamodb:Scan
              - dynamodb:GetItem
              - dynamodb:PutItem
              - dynamodb:UpdateItem
              - dynamodb:DeleteItem
          Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:custom.ammConfigTableName}"

package:
    exclude:
        - node_modules/@perp/contract/node_modules/**

custom:
    serverless-offline:
        port: 3002
        noTimeout: true

    webpack:
        webpackConfig: 'webpack.config.js'
        includeModules: false
        packager: 'npm'

    ammConfigTableName: arbitrageur-config-${self:provider.stage}

functions:
    arbitrageur:
        handler: build/src/schedule.handler
        reservedConcurrency: 1
        maximumRetryAttempts: 0
        environment:
            AMM_CONFIG_TABLE_NAME: ${self:custom.ammConfigTableName}
        events:
            - schedule: rate(1 minute)

    telegramBot:
        handler: build/src/bot.telegramHandler
        events:
            - http:
                  path: _webhook/tg/${env:TELEGRAM_WEBHOOK_PATH_SECRET}
                  method: post

    prometheusMetrics:
        handler: build/src/metrics.prometheusHandler
        events:
            - http:
                  path: _metrics/prom/${env:PROMETHEUS_METRICS_PATH_SECRET}
                  method: get

resources:
    Resources:
        AmmConfigTable:
            Type: AWS::DynamoDB::Table
            Properties:
                TableName: ${self:custom.ammConfigTableName}
                AttributeDefinitions:
                    - AttributeName: ammPair
                      AttributeType: S
                KeySchema:
                    - AttributeName: ammPair
                      KeyType: HASH
                ProvisionedThroughput:
                    ReadCapacityUnits: 1
                    WriteCapacityUnits: 1
